// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sum.proto

package grpc.sum;

public interface SumRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SumRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 numbers = 1;</code>
   */
  java.util.List<java.lang.Integer> getNumbersList();
  /**
   * <code>repeated int32 numbers = 1;</code>
   */
  int getNumbersCount();
  /**
   * <code>repeated int32 numbers = 1;</code>
   */
  int getNumbers(int index);
}
