// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sum.proto

package grpc.sum;

public interface SumResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SumResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 result = 1;</code>
   */
  int getResult();
}
